---
title: "Untitled"
author: "Ariel Marcy"
date: "12/3/2020"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/Work/Science/Research/2020 UNL DBER/Co-Teaching/teach-coord/Data/Raw/")
```

## Read in data and packages
```{r}
library(stringr)

raw <- read.csv("~/Documents/Work/Science/Research/2020 UNL DBER/Co-Teaching/teach-coord/Data/Raw/SurveyDataDI.csv", header = TRUE)
```

## Fix Academic Rank to ascend with rank
```{r}
t.data <- raw
t.data$AcadRank <- t.data$AcadRank * 10  # mark old numbers

# Sub in new ones
t.data$AcadRank[which(t.data$AcadRank == 10)] <- 6  # Prof
t.data$AcadRank[which(t.data$AcadRank == 20)] <- 5  # A/Prof
t.data$AcadRank[which(t.data$AcadRank == 30)] <- 4  # Asst P
t.data$AcadRank[which(t.data$AcadRank == 40)] <- 3  # lecturer
t.data$AcadRank[which(t.data$AcadRank == 50)] <- 2  # visiting
t.data$AcadRank[which(t.data$AcadRank == 60)] <- 1  # pre-prof (post-doc)
t.data$AcadRank[which(t.data$AcadRank == 70)] <- 1  # pre-prof (grad student)

rank.names <- c("PreProf", "Visit.", "Lecture", "Asst. P", "A/Prof", "Prof")

t.data$CoordPattern <- as.character(raw$CoordPattern) 
```

## Redefine "Coordination Pattern" into 3x4 table of broader categories
```{r}
u.coords <- unique(t.data$CoordPattern) 

# Subset by discipline [optional]
t.data <- t.data[which(t.data$Discipline == 3), ]

# Subset the datasets
text.1 <- t.data[str_which(t.data$CoordPattern, "1[123][123][123]"), ]  # solo
text.2 <- t.data[str_which(t.data$CoordPattern, "2[123][123][123]"), ]  # coll
text.3 <- t.data[str_which(t.data$CoordPattern, "3[123][123][123]"), ]  # cont

exam.1 <- t.data[str_which(t.data$CoordPattern, "[123]1[123][123]"), ]  # solo
exam.2 <- t.data[str_which(t.data$CoordPattern, "[123]2[123][123]"), ]  # coll
exam.3 <- t.data[str_which(t.data$CoordPattern, "[123]3[123][123]"), ]  # cont

cont.1 <- t.data[str_which(t.data$CoordPattern, "[123][123]1[123]"), ]  # solo
cont.2 <- t.data[str_which(t.data$CoordPattern, "[123][123]2[123]"), ]  # coll
cont.3 <- t.data[str_which(t.data$CoordPattern, "[123][123]3[123]"), ]  # cont

inst.1 <- t.data[str_which(t.data$CoordPattern, "[123][123][123]1"), ]  # solo
inst.2 <- t.data[str_which(t.data$CoordPattern, "[123][123][123]2"), ]  # coll
inst.3 <- t.data[str_which(t.data$CoordPattern, "[123][123][123]3"), ]  # cont
```

## Function to get important values by dataset
```{r}
MakeTECItable <- function(dataset) {
        # Get total n
        dataset <- dataset[complete.cases(dataset$RBISuse), ]
        N <- dim(dataset)[1]
        
        # Get percent RBIS
        perRBIS <- signif(((length(which(dataset$RBISuse == 2)) / N ) *100), 3)
        
        # Get the top three coordination patterns
        pat.freq <- table(dataset$CoordPattern)
        top.3 <- dimnames(pat.freq[order(pat.freq, decreasing = T)])[[1]][1:3]
        top.3.n <- pat.freq[order(pat.freq, decreasing = TRUE)[1:3]]
        top.3.eng <- paste(top.3[1], " (n=", top.3.n[1], "), ", top.3[2], " (n=", top.3.n[2], "), ", top.3[3], " (n=", top.3.n[3], ")", sep = "")
        TECIbox <- list(N, perRBIS, top.3.eng)
        return(TECIbox)        
        
}

# Print results for rough draft table
MakeTECItable(inst.3)
MakeTECItable(inst.2)
MakeTECItable(inst.1)
```

## Test 100 randomizations for entire dataset
```{r}
r.per <- vector("numeric", length = 100)
conf.table <- data.frame(cell = 1:12, mean = 0, low = 0, high = 0)
test.data <- t.data[complete.cases(t.data$RBISuse), ]
CoordPatterns <- c("1[123][123][123]", "2[123][123][123]", "3[123][123][123]",
                   "[123]1[123][123]", "[123]2[123][123]", "[123]3[123][123]",
                   "[123][123]1[123]", "[123][123]2[123]", "[123][123]3[123]",
                   "[123][123][123]1", "[123][123][123]2", "[123][123][123]3")

# Calculate standard deviation (alpha = 0.001) for table of all disciplines
for (pat in 1:length(CoordPatterns)){ # calculate mean for each pattern
        for(n in 1:100) {  # randomize RBIS use
                test.data$Rand <- sample(test.data$RBISuse)  
                test.sub <- test.data[str_which(test.data$CoordPattern, CoordPatterns[pat]), ] 
                r.per[n] <- ((length(which(test.sub$Rand == 2)) / dim(test.sub)[1]) * 100)  # % RBIS in that cell for n randomization
        }
        t.result <- t.test(r.per, conf.level = 0.999)
        conf.table[pat, 2] <- mean(r.per)
        conf.table[pat, 3] <- t.result$conf.int[1]
        conf.table[pat, 4] <- t.result$conf.int[2]
}
```

## Test 100 randomizations with discipline subsetting
```{r}
r.per <- vector("numeric", length = 100)
conf.table <- data.frame(cell = 1:12, mean = 0, low = 0, high = 0)
test.data <- t.data[complete.cases(t.data$RBISuse), ]
CoordPatterns <- c("1[123][123][123]", "2[123][123][123]", "3[123][123][123]",
                   "[123]1[123][123]", "[123]2[123][123]", "[123]3[123][123]",
                   "[123][123]1[123]", "[123][123]2[123]", "[123][123]3[123]",
                   "[123][123][123]1", "[123][123][123]2", "[123][123][123]3")

# Calculate standard deviation (alpha = 0.001) for table of one discipline (specify by 1, 2, or 3 on 4th line:)
for (pat in 1:length(CoordPatterns)){ # calculate mean for each pattern
        for(n in 1:100) {  # randomize RBIS use
                test.data$Rand <- sample(test.data$RBISuse)  
                test.sub <- test.data[which(test.data$Discipline == 1), ] # subset by discipline (1 = chemistry, 2 = math, 3 = physics)
                test.sub <- test.sub[str_which(test.sub$CoordPattern, CoordPatterns[pat]), ] 
                r.per[n] <- ((length(which(test.sub$Rand == 2)) / dim(test.sub)[1]) * 100)  # % RBIS in that cell for n randomization
        }
        t.result <- t.test(r.per, conf.level = 0.999)
        conf.table[pat, 2] <- mean(r.per)
        conf.table[pat, 3] <- t.result$conf.int[1]
        conf.table[pat, 4] <- t.result$conf.int[2]
}
```

## Test 100 randomizations withIN disciplines
```{r}
r.per <- vector("numeric", length = 100)
conf.table <- data.frame(cell = 1:12, mean = 0, low = 0, high = 0)
test.data <- t.data[complete.cases(t.data$RBISuse), ]
CoordPatterns <- c("1[123][123][123]", "2[123][123][123]", "3[123][123][123]",
                   "[123]1[123][123]", "[123]2[123][123]", "[123]3[123][123]",
                   "[123][123]1[123]", "[123][123]2[123]", "[123][123]3[123]",
                   "[123][123][123]1", "[123][123][123]2", "[123][123][123]3")

# Calculate standard deviation (alpha = 0.001) for table of one discipline (specify by 1, 2, or 3 on 4th line:)
for (pat in 1:length(CoordPatterns)){ # calculate mean for each pattern
        for(n in 1:100) {  # randomize RBIS use
                test.sub <- test.data[which(test.data$Discipline == 3), ] # subset by discipline (1 = chemistry, 2 = math, 3 = physics)
                test.sub$Rand <- sample(test.sub$RBISuse) 
                test.sub <- test.sub[str_which(test.sub$CoordPattern, CoordPatterns[pat]), ] 
                r.per[n] <- ((length(which(test.sub$Rand == 2)) / dim(test.sub)[1]) * 100)  # % RBIS in that cell for n randomization
        }
        t.result <- t.test(r.per, conf.level = 0.999)
        conf.table[pat, 2] <- mean(r.per)
        conf.table[pat, 3] <- t.result$conf.int[1]
        conf.table[pat, 4] <- t.result$conf.int[2]
}
```
